# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f81598b8bf15bfdd4165afb29ef957c4"
name = "fs-custom-badges"
application_url = "https://fs-custom-badges.vercel.app"
embedded = true

[app_proxy]
url = "https://fs-custom-badges.vercel.app/api/badges"
subpath = "badges"
prefix = "apps"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
scopes = "write_app_proxy"

[auth]
redirect_urls = [
  "https://fs-custom-badges.vercel.app/auth/callback",
  "https://fs-custom-badges.vercel.app/auth/shopify/callback",
  "https://fs-custom-badges.vercel.app/api/auth"
]

[build]
automatically_update_urls_on_dev = true